<?php

/**
 * @file
 * Contains adminx.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function adminx_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the adminx module.
    case 'help.page.adminx':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adminx') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function adminx_theme() {
  return [
    'adminx' => [
      'render element' => 'children',
    ],
  ];
}
